blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: https://github.com/nikashelia/wal-react-native/discussions
    about: Please use GitHub Discussions for questions.


