/**
 * Kotlin emitter (Android port). Consumes the same language-neutral model as gen-swift.ts.
 *
 * Status: scaffold. It reproduces the type/operation catalogue so the Android core can be diffed
 * against the iOS core for parity (same type names, property names, operationIds, route ids, token
 * names). Full Kotlin DTO / operation emission lands with the Kotlin migration; the structure here is
 * intentionally a one-to-one mirror of gen-swift.ts so both emitters evolve together.
 *
 * Run explicitly: `npm run gen:kotlin`. It is NOT part of `npm run gen` or the drift check yet.
 */
import fs from 'node:fs';
import path from 'node:path';
import { ModelBuilder, camel, pascal } from './openapi-model.js';
import { KOTLIN_API_GENERATED_DIR, KOTLIN_CORE_GENERATED_DIR, OPENAPI_JSON, ROUTES_JSON, TOKENS_JSON } from './paths.js';

const HEADER = `// Generated by native/shared/codegen (npm run gen:kotlin). DO NOT EDIT.
// Source of truth: native/shared/**. Re-run the generator instead of editing this file.
`;

export interface KotlinCatalog {
  types: string[];
  operations: string[];
  routes: string[];
  tokens: string[];
}

/** Language-neutral catalogue both emitters must agree on; the parity test compares this with Swift. */
export function buildCatalog(): KotlinCatalog {
  const model = new ModelBuilder(OPENAPI_JSON).build();
  const routes = JSON.parse(fs.readFileSync(ROUTES_JSON, 'utf8'));
  const tokens = JSON.parse(fs.readFileSync(TOKENS_JSON, 'utf8'));
  return {
    types: model.types.map((t) => pascal(t.name)),
    operations: model.operations.map((o) => o.operationId),
    routes: routes.routes.map((r: { id: string }) => camel(r.id)),
    tokens: Object.keys(tokens.colors),
  };
}

export function generateKotlinCatalog(): { path: string; contents: string }[] {
  const catalog = buildCatalog();
  const list = (items: string[]) => items.map((i) => `        "${i}",`).join('\n');
  const contents = `${HEADER}
package ge.wal.core.generated

/** Parity catalogue mirrored from the iOS core (see Operations.allOperationIds / RouteID / Tokens.Colors). */
object Catalog {
    val operationIds: List<String> = listOf(
${list(catalog.operations)}
    )

    val routeIds: List<String> = listOf(
${list(catalog.routes)}
    )

    val colorTokens: List<String> = listOf(
${list(catalog.tokens)}
    )
}
`;
  return [
    { path: path.join(KOTLIN_CORE_GENERATED_DIR, 'Catalog.kt'), contents },
    { path: path.join(KOTLIN_API_GENERATED_DIR, '.gitkeep'), contents: '' },
  ];
}

if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) {
  for (const f of generateKotlinCatalog()) {
    fs.mkdirSync(path.dirname(f.path), { recursive: true });
    fs.writeFileSync(f.path, f.contents);
    console.log(`wrote ${path.relative(process.cwd(), f.path)}`);
  }
}
