/**
 * Swift emitter. Consumes the language-neutral model (openapi-model.ts), the design tokens,
 * the route table and the locale files, and writes:
 *
 *   native/ios/WALCore/Sources/WALAPI/Generated/Models.swift      Codable DTOs
 *   native/ios/WALCore/Sources/WALAPI/Generated/Operations.swift  one APIOperation per endpoint
 *   native/ios/WALCore/Sources/WALCore/Generated/Tokens.swift     design tokens as pure data
 *   native/ios/WALCore/Sources/WALCore/Generated/Routes.swift     Route enum + descriptors
 *   native/ios/WALCore/Sources/WALCore/Generated/L10nKeys.swift   translation keys
 *   native/ios/WALCore/Sources/WALCore/Resources/Locales/*.json   copied locale bundles
 *
 * Everything emitted here is deterministic so `check:drift` can diff the output against git.
 * The Kotlin emitter (gen-kotlin.ts) mirrors this file one-to-one.
 */
import fs from 'node:fs';
import path from 'node:path';
import {
  ModelBuilder,
  camel,
  pascal,
  type ApiModel,
  type NamedType,
  type ObjectType,
  type OperationModel,
  type Parameter,
  type Property,
  type TypeRef,
} from './openapi-model.js';
import {
  OPENAPI_JSON,
  ROUTES_JSON,
  RN_LOCALES_DIR,
  SWIFT_API_GENERATED_DIR,
  SWIFT_CORE_GENERATED_DIR,
  SWIFT_CORE_RESOURCES_LOCALES_DIR,
  TOKENS_JSON,
} from './paths.js';

const HEADER = `// Generated by native/shared/codegen (npm run gen:swift). DO NOT EDIT.
// Source of truth: native/shared/**. Re-run the generator instead of editing this file.
`;

// ---------------------------------------------------------------------------
// Identifier helpers
// ---------------------------------------------------------------------------

const SWIFT_KEYWORDS = new Set([
  'associatedtype', 'class', 'deinit', 'enum', 'extension', 'fileprivate', 'func', 'import', 'init', 'inout',
  'internal', 'let', 'open', 'operator', 'private', 'precedencegroup', 'protocol', 'public', 'rethrows', 'static',
  'struct', 'subscript', 'typealias', 'var', 'break', 'case', 'catch', 'continue', 'default', 'defer', 'do',
  'else', 'fallthrough', 'for', 'guard', 'if', 'in', 'repeat', 'return', 'throw', 'switch', 'where', 'while',
  'Any', 'as', 'await', 'false', 'is', 'nil', 'self', 'Self', 'super', 'throws', 'true', 'try', 'some', 'any',
]);

/** Members that would clash with synthesized protocol requirements on a Codable/Hashable struct. */
const RESERVED_MEMBERS = new Set(['hashValue', 'Type', 'CodingKeys', 'description_']);

/** Foundation / stdlib names a DTO must not shadow. */
const TYPE_BLOCKLIST = new Set([
  'Error', 'Data', 'Date', 'URL', 'Result', 'Task', 'Notification', 'Set', 'Character', 'Bundle', 'Thread',
  'Operation', 'Timer', 'Stream', 'Process', 'Locale', 'Unit', 'Progress', 'Expression', 'Measurement', 'Decimal',
  'Optional', 'Array', 'Dictionary', 'String', 'Int', 'Double', 'Bool', 'Float', 'Never', 'Void', 'Encoder', 'Decoder',
  'Operations', 'JSONValue', 'MultipartFile', 'EmptyResponse', 'NoBody', 'NoParameters', 'HTTPMethod', 'BodyEncoding',
]);

function ident(name: string): string {
  if (SWIFT_KEYWORDS.has(name)) return `\`${name}\``;
  if (RESERVED_MEMBERS.has(name)) return `${name}Value`;
  return name;
}

function typeName(name: string): string {
  const p = pascal(name);
  return TYPE_BLOCKLIST.has(p) ? `${p}Model` : p;
}

function enumCaseName(value: string): string {
  if (value === '') return 'empty';
  let c = camel(value);
  if (/^[0-9]/.test(value)) c = `_${camel(value)}`.replace(/^__/, '_');
  return ident(c);
}

function swiftString(s: string): string {
  return JSON.stringify(s);
}

function docComment(text: string | undefined, indent: string): string {
  if (!text) return '';
  return text
    .split('\n')
    .filter((l) => l.trim().length > 0)
    .map((l) => `${indent}/// ${l.trim()}`)
    .join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Type mapping
// ---------------------------------------------------------------------------

function swiftType(t: TypeRef): string {
  switch (t.kind) {
    case 'string':
      return 'String';
    case 'number':
      return 'Double';
    case 'integer':
      return 'Int';
    case 'boolean':
      return 'Bool';
    case 'any':
      return 'JSONValue';
    case 'file':
      return 'MultipartFile';
    case 'array':
      return `[${swiftType(t.items)}]`;
    case 'map':
      return `[String: ${swiftType(t.values)}]`;
    case 'ref':
    case 'enum':
    case 'object':
      return typeName(t.name);
  }
}

/** Direct (non-collection) references between named types, used for recursion detection. */
function directRefs(t: TypeRef, types: Map<string, NamedType>): string[] {
  switch (t.kind) {
    case 'ref':
    case 'object': {
      const target = types.get(t.name);
      if (target?.kind === 'alias') return directRefs(target.type, types);
      return target?.kind === 'object' ? [t.name] : [];
    }
    default:
      return [];
  }
}

function findRecursiveProperties(types: Map<string, NamedType>): Set<string> {
  // Returns "Type.property" pairs that must be boxed to break value-type recursion.
  const boxed = new Set<string>();
  const graph = new Map<string, { prop: string; to: string }[]>();
  for (const t of types.values()) {
    if (t.kind !== 'object') continue;
    graph.set(
      t.name,
      t.properties.flatMap((p) => directRefs(p.type, types).map((to) => ({ prop: p.name, to }))),
    );
  }
  const visiting = new Set<string>();
  const done = new Set<string>();
  const dfs = (node: string) => {
    if (done.has(node)) return;
    visiting.add(node);
    for (const edge of graph.get(node) ?? []) {
      if (visiting.has(edge.to)) {
        boxed.add(`${node}.${edge.prop}`);
      } else if (!done.has(edge.to)) {
        dfs(edge.to);
      }
    }
    visiting.delete(node);
    done.add(node);
  };
  for (const name of graph.keys()) dfs(name);
  return boxed;
}

// ---------------------------------------------------------------------------
// Models.swift
// ---------------------------------------------------------------------------

function emitProperty(owner: string, p: Property, boxed: Set<string>): string {
  const optional = p.optional || p.nullable;
  const base = swiftType(p.type);
  const type = optional ? `${base}?` : base;
  const wrapper = boxed.has(`${owner}.${p.name}`) ? '@Indirect ' : '';
  return `${docComment(p.description, '    ')}    ${wrapper}public var ${ident(p.name)}: ${type}`;
}

function emitCodingKeys(props: { wireName: string; name: string }[]): string {
  if (props.length === 0) return '';
  const lines = props.map((p) =>
    p.wireName === p.name ? `        case ${ident(p.name)}` : `        case ${ident(p.name)} = ${swiftString(p.wireName)}`,
  );
  return `\n    public enum CodingKeys: String, CodingKey {\n${lines.join('\n')}\n    }\n`;
}

function emitInit(owner: string, props: Property[], boxed: Set<string>): string {
  if (props.length === 0) return '    public init() {}\n';
  const params = props.map((p) => {
    const optional = p.optional || p.nullable;
    const type = swiftType(p.type);
    return `${ident(p.name)}: ${type}${optional ? '? = nil' : ''}`;
  });
  const assigns = props.map((p) => {
    const lhs = boxed.has(`${owner}.${p.name}`) ? `self.${ident(p.name)}` : `self.${ident(p.name)}`;
    const rhs = boxed.has(`${owner}.${p.name}`) ? ident(p.name) : ident(p.name);
    return `        ${lhs} = ${rhs}`;
  });
  return `    public init(\n        ${params.join(',\n        ')}\n    ) {\n${assigns.join('\n')}\n    }\n`;
}

function multipartTextExpr(t: TypeRef, value: string): string {
  switch (t.kind) {
    case 'string':
      return value;
    case 'integer':
    case 'number':
    case 'boolean':
      return `MultipartText.scalar(${value})`;
    case 'enum':
      return `${value}.rawValue`;
    default:
      return `MultipartText.json(${value})`;
  }
}

function emitMultipart(obj: ObjectType): string {
  const lines: string[] = [];
  for (const p of obj.properties) {
    const optional = p.optional || p.nullable;
    const name = ident(p.name);
    const wire = swiftString(p.wireName);
    const value = optional ? 'value' : name;
    const body = (() => {
      const t = p.type;
      if (t.kind === 'file') return `parts.append(.file(name: ${wire}, file: ${value}))`;
      if (t.kind === 'array' && t.items.kind === 'file') return `for file in ${value} { parts.append(.file(name: ${wire}, file: file)) }`;
      if (t.kind === 'array') return `for item in ${value} { parts.append(.text(name: ${wire}, value: ${multipartTextExpr(t.items, 'item')})) }`;
      return `parts.append(.text(name: ${wire}, value: ${multipartTextExpr(t, value)}))`;
    })();
    lines.push(optional ? `        if let value = ${name} { ${body} }` : `        ${body}`);
  }
  return `\nextension ${typeName(obj.name)}: MultipartEncodable {\n    public func multipartParts() -> [MultipartPart] {\n        var parts: [MultipartPart] = []\n${lines.join('\n')}\n        return parts\n    }\n}\n`;
}

function emitObject(obj: ObjectType, boxed: Set<string>): string {
  const name = typeName(obj.name);
  const props = obj.properties.map((p) => emitProperty(obj.name, p, boxed)).join('\n');
  let out = `${docComment(obj.description, '')}public struct ${name}: Codable, Hashable, Sendable {\n`;
  if (obj.properties.length > 0) out += `${props}\n\n`;
  out += emitInit(obj.name, obj.properties, boxed);
  out += emitCodingKeys(obj.properties);
  out += '}\n';
  if (obj.multipart) out += emitMultipart(obj);
  return out;
}

/**
 * Enums are emitted as extensible string wrappers so an unknown server value never fails decoding
 * (the RN app treats these as plain strings). Known values are exposed as static members.
 */
function emitEnum(name: string, values: string[], description?: string): string {
  const swiftName = typeName(name);
  const seen = new Set<string>();
  const cases = values.map((v) => {
    let c = enumCaseName(v);
    while (seen.has(c)) c = `${c}_`;
    seen.add(c);
    return `    public static let ${c} = ${swiftName}(rawValue: ${swiftString(v)})`;
  });
  const known = [...seen].map((c) => `.${c.replace(/`/g, '')}`).join(', ');
  return `${docComment(description, '')}public struct ${swiftName}: RawRepresentable, Codable, Hashable, Sendable, ExpressibleByStringLiteral, CustomStringConvertible {
    public let rawValue: String
    public init(rawValue: String) { self.rawValue = rawValue }
    public init(stringLiteral value: String) { self.rawValue = value }
    public init(from decoder: Decoder) throws { self.rawValue = try decoder.singleValueContainer().decode(String.self) }
    public func encode(to encoder: Encoder) throws { var c = encoder.singleValueContainer(); try c.encode(rawValue) }
    public var description: String { rawValue }
    public var isKnown: Bool { Self.known.contains(self) }
${cases.join('\n')}
    public static let known: [${swiftName}] = [${known}]
}
`;
}

function emitModels(model: ApiModel, types: Map<string, NamedType>): string {
  const boxed = findRecursiveProperties(types);
  const chunks: string[] = [HEADER, 'import Foundation\n'];
  for (const t of model.types) {
    switch (t.kind) {
      case 'object':
        chunks.push(emitObject(t, boxed));
        break;
      case 'enum':
        chunks.push(emitEnum(t.name, t.values, t.description));
        break;
      case 'alias':
        chunks.push(`${docComment(t.description, '')}public typealias ${typeName(t.name)} = ${swiftType(t.type)}\n`);
        break;
    }
  }
  return chunks.join('\n');
}

// ---------------------------------------------------------------------------
// Operations.swift
// ---------------------------------------------------------------------------

function emitParamStruct(structName: string, params: Parameter[], kind: 'path' | 'query' | 'header'): string {
  if (params.length === 0) return `        public typealias ${structName} = NoParameters\n`;
  const props = params.map((p) => {
    const type = swiftType(p.type);
    return `${docComment(p.description, '        ')}        public var ${ident(p.name)}: ${p.required ? type : `${type}?`}`;
  });
  const initParams = params.map((p) => `${ident(p.name)}: ${swiftType(p.type)}${p.required ? '' : '? = nil'}`);
  const assigns = params.map((p) => `            self.${ident(p.name)} = ${ident(p.name)}`);
  let conformance = 'Encodable, Hashable, Sendable';
  let extra = '';
  if (kind === 'path') {
    conformance += ', PathParameters';
    extra = `        public var pathValues: [String: String] {\n            [${params.map((p) => `${swiftString(p.wireName)}: ParameterValue.string(${ident(p.name)})`).join(', ')}]\n        }\n`;
  } else if (kind === 'query') {
    conformance += ', QueryParameters';
    extra = `        public var queryItems: [URLQueryItem] {\n            var items: [URLQueryItem] = []\n${params
      .map((p) => `            items.append(contentsOf: ParameterValue.queryItems(${swiftString(p.wireName)}, ${ident(p.name)}))`)
      .join('\n')}\n            return items\n        }\n`;
  } else {
    conformance += ', HeaderParameters';
    extra = `        public var headerValues: [String: String] {\n            var values: [String: String] = [:]\n${params
      .map((p) => `            ParameterValue.assign(&values, ${swiftString(p.wireName)}, ${ident(p.name)})`)
      .join('\n')}\n            return values\n        }\n`;
  }
  return `    public struct ${structName}: ${conformance} {
${props.join('\n')}

        public init(${initParams.join(', ')}) {
${assigns.join('\n')}
        }
${extra}${emitCodingKeys(params).replace(/\n {4}/g, '\n        ')}    }
`;
}

function emitOperation(op: OperationModel): string {
  const name = typeName(op.typeName);
  const bodyType = op.body ? swiftType(op.body.type) : 'NoBody';
  const bodyEncoding = !op.body ? '.none' : op.body.multipart ? '.multipart' : '.json';
  const responseType = op.response ? swiftType(op.response) : 'EmptyResponse';
  const hasPath = op.pathParams.length > 0;
  const hasQuery = op.queryParams.length > 0;
  const hasHeaders = op.headerParams.length > 0;

  const initParams: string[] = [];
  const initAssigns: string[] = [];
  if (hasPath) {
    initParams.push('path: Path');
    initAssigns.push('        self.path = path');
  } else initAssigns.push('        self.path = NoParameters()');
  if (hasQuery) {
    initParams.push(op.queryParams.every((p) => !p.required) ? 'query: Query = Query()' : 'query: Query');
    initAssigns.push('        self.query = query');
  } else initAssigns.push('        self.query = NoParameters()');
  if (hasHeaders) {
    initParams.push(op.headerParams.every((p) => !p.required) ? 'headers: Headers = Headers()' : 'headers: Headers');
    initAssigns.push('        self.headers = headers');
  } else initAssigns.push('        self.headers = NoParameters()');
  if (op.body) {
    initParams.push(op.body.required ? `body: ${bodyType}` : `body: ${bodyType}? = nil`);
    initAssigns.push('        self.body = body');
  } else initAssigns.push('        self.body = nil');

  return `${docComment(op.description, '    ')}    /// \`${op.method} ${op.pathTemplate}\` (tag: ${op.tag})
    public struct ${name}: APIOperation {
        public static let operationId = ${swiftString(op.operationId)}
        public static let method: HTTPMethod = .${op.method.toLowerCase()}
        public static let pathTemplate = ${swiftString(op.pathTemplate)}
        public static let bodyEncoding: BodyEncoding = ${bodyEncoding}
        public typealias Body = ${bodyType}
        public typealias Response = ${responseType}

${emitParamStruct('Path', op.pathParams, 'path')}${emitParamStruct('Query', op.queryParams, 'query')}${emitParamStruct('Headers', op.headerParams, 'header')}
        public var path: Path
        public var query: Query
        public var headers: Headers
        public var body: Body?

        public init(${initParams.join(', ')}) {
${initAssigns.join('\n')}
        }
    }
`;
}

function emitOperations(model: ApiModel): string {
  const ops = model.operations.map(emitOperation).join('\n');
  const ids = model.operations.map((o) => `        ${swiftString(o.operationId)},`).join('\n');
  return `${HEADER}
import Foundation

/// Namespace for every generated API operation. One struct per OpenAPI operation.
public enum Operations {
${ops}
    /// Every operationId, in stable order (used by walctl and drift tests).
    public static let allOperationIds: [String] = [
${ids}
    ]
}
`;
}

// ---------------------------------------------------------------------------
// Tokens.swift
// ---------------------------------------------------------------------------

type JsonAny = string | number | boolean | null | JsonAny[] | { [k: string]: JsonAny };

const TOKEN_META_KEYS = new Set(['$schema', 'description', 'note']);

function isColorToken(v: JsonAny): v is { light: string; dark: string } {
  return !!v && typeof v === 'object' && !Array.isArray(v) && typeof v.light === 'string' && typeof v.dark === 'string';
}

function numberLiteral(n: number): { type: string; literal: string } {
  return Number.isInteger(n) ? { type: 'Int', literal: String(n) } : { type: 'Double', literal: String(n) };
}

function emitTokenNamespace(name: string, obj: { [k: string]: JsonAny }, indent: string): string {
  const pad = indent + '    ';
  const lines: string[] = [];
  const description = typeof obj.description === 'string' ? obj.description : undefined;
  lines.push(`${docComment(description, indent)}${indent}public enum ${pascal(name)} {`);
  const colorEntries: string[] = [];
  for (const [key, value] of Object.entries(obj)) {
    if (TOKEN_META_KEYS.has(key)) continue;
    const member = ident(camel(key));
    if (isColorToken(value)) {
      lines.push(`${pad}public static let ${member} = ColorToken(light: ${swiftString(value.light)}, dark: ${swiftString(value.dark)})`);
      colorEntries.push(`${swiftString(key)}: ${member}`);
    } else if (typeof value === 'string') {
      lines.push(`${pad}public static let ${member}: String = ${swiftString(value)}`);
    } else if (typeof value === 'number') {
      const { type, literal } = numberLiteral(value);
      lines.push(`${pad}public static let ${member}: ${type} = ${literal}`);
    } else if (typeof value === 'boolean') {
      lines.push(`${pad}public static let ${member}: Bool = ${value}`);
    } else if (Array.isArray(value)) {
      if (value.every((v) => typeof v === 'number')) {
        lines.push(`${pad}public static let ${member}: [Double] = [${(value as number[]).map(String).join(', ')}]`);
      } else if (value.every((v) => typeof v === 'string')) {
        lines.push(`${pad}public static let ${member}: [String] = [${(value as string[]).map(swiftString).join(', ')}]`);
      } else {
        throw new Error(`Unsupported token array at ${name}.${key}`);
      }
    } else if (value && typeof value === 'object') {
      lines.push(emitTokenNamespace(key, value, pad));
    }
  }
  if (colorEntries.length > 0) {
    lines.push(`${pad}public static let all: [String: ColorToken] = [\n${colorEntries.map((e) => `${pad}    ${e},`).join('\n')}\n${pad}]`);
  }
  lines.push(`${indent}}`);
  return lines.join('\n');
}

function emitTokens(tokens: { [k: string]: JsonAny }): string {
  const body = Object.entries(tokens)
    .filter(([k, v]) => !TOKEN_META_KEYS.has(k) && v && typeof v === 'object' && !Array.isArray(v))
    .map(([k, v]) => emitTokenNamespace(k, v as { [k: string]: JsonAny }, '    '))
    .join('\n\n');
  return `${HEADER}
import Foundation

/// A colour pair resolved per colour scheme. Values are CSS strings (#rrggbb, #rrggbbaa or rgba(r,g,b,a)).
public struct ColorToken: Hashable, Sendable {
    public let light: String
    public let dark: String
    public init(light: String, dark: String) {
        self.light = light
        self.dark = dark
    }
    public func resolved(dark isDark: Bool) -> String { isDark ? dark : light }
}

/// Design tokens mirrored from native/shared/design/tokens.json. Pure data; no UIKit/SwiftUI.
public enum Tokens {
${body}
}
`;
}

// ---------------------------------------------------------------------------
// Routes.swift
// ---------------------------------------------------------------------------

interface RouteParam { name: string; type: 'string' | 'bool' | 'int'; optional?: boolean }
interface RouteJson {
  id: string;
  rnPath: string;
  stack: string;
  presentation: string;
  animation?: string;
  animationDurationMs?: number;
  params: RouteParam[];
  header?: string;
  headerTitle?: string;
  headerTitleKey?: string;
  headerHideBack?: boolean;
  headerRight?: string;
  headerShowTabs?: boolean;
  headerLogoutOnBack?: boolean;
  headerWithInsets?: boolean;
  backgroundColor?: string;
  outOfScope?: string;
  note?: string;
}
interface TabJson {
  id: string;
  rnGroup: string;
  initialRoute: string;
  iconFocused: string;
  iconUnfocused: string;
  focusedScale: number;
  tabPressResetsStack?: boolean;
}
interface RoutesJson {
  tabs: TabJson[];
  routes: RouteJson[];
  stacks: Record<string, string>;
  deepLinks: { scheme: string; associatedDomain: string; patterns: { match: string; route: string; note?: string }[] };
  pushNotificationRouting: { type: string; requires: string[]; route: string }[];
}

function routeParamType(p: RouteParam): string {
  const base = p.type === 'bool' ? 'Bool' : p.type === 'int' ? 'Int' : 'String';
  return p.optional ? `${base}?` : base;
}

function optString(v: string | undefined): string {
  return v === undefined ? 'nil' : swiftString(v);
}

function emitRoutes(routes: RoutesJson): string {
  const routeIds = routes.routes.map((r) => `    case ${ident(camel(r.id))}`).join('\n');
  const stackIds = Object.keys(routes.stacks).map((s) => `    case ${ident(camel(s))}`).join('\n');
  const presentations = [...new Set(routes.routes.map((r) => r.presentation))].sort();
  const headers = [...new Set(routes.routes.map((r) => r.header ?? 'none'))].sort();

  const cases = routes.routes.map((r) => {
    if (r.params.length === 0) return `    case ${ident(camel(r.id))}`;
    const assoc = r.params.map((p) => `${ident(camel(p.name))}: ${routeParamType(p)}${p.optional ? ' = nil' : ''}`);
    return `    case ${ident(camel(r.id))}(${assoc.join(', ')})`;
  });

  const idSwitch = routes.routes.map((r) => {
    const pattern = r.params.length === 0 ? `.${camel(r.id)}` : `.${camel(r.id)}`;
    return `        case ${pattern}: return .${camel(r.id)}`;
  });

  const paramSwitch = routes.routes.map((r) => {
    if (r.params.length === 0) return `        case .${camel(r.id)}: return [:]`;
    const binds = r.params.map((p) => `let ${ident(camel(p.name))}`).join(', ');
    const entries = r.params.map((p) => {
      const v = ident(camel(p.name));
      const conv = p.type === 'string' ? (p.optional ? `${v}` : `${v}`) : p.optional ? `${v}.map(String.init)` : `String(${v})`;
      return `${swiftString(p.name)}: ${conv}`;
    });
    return `        case .${camel(r.id)}(${binds}):\n            return [${entries.join(', ')}].compactMapValues { $0 }`;
  });

  const descriptors = routes.routes.map((r) => {
    const params = r.params
      .map((p) => `RouteParamDescriptor(name: ${swiftString(p.name)}, type: .${p.type}, optional: ${!!p.optional})`)
      .join(', ');
    return `        .${camel(r.id)}: RouteDescriptor(
            id: .${camel(r.id)},
            rnPath: ${swiftString(r.rnPath)},
            stack: .${camel(r.stack)},
            presentation: .${camel(r.presentation)},
            animation: ${optString(r.animation)},
            animationDurationMs: ${r.animationDurationMs ?? 'nil'},
            params: [${params}],
            header: .${ident(camel(r.header ?? 'none'))},
            headerTitle: ${optString(r.headerTitle)},
            headerTitleKey: ${optString(r.headerTitleKey)},
            headerHideBack: ${!!r.headerHideBack},
            headerRight: ${optString(r.headerRight)},
            headerShowTabs: ${!!r.headerShowTabs},
            headerLogoutOnBack: ${!!r.headerLogoutOnBack},
            headerWithInsets: ${!!r.headerWithInsets},
            backgroundColor: ${optString(r.backgroundColor)},
            outOfScope: ${optString(r.outOfScope)}
        ),`;
  });

  const tabs = routes.tabs.map(
    (t) => `        TabDescriptor(id: .${camel(t.id)}, initialRoute: .${camel(t.initialRoute)}, iconFocused: ${swiftString(t.iconFocused)}, iconUnfocused: ${swiftString(t.iconUnfocused)}, focusedScale: ${t.focusedScale.toFixed(2)}, tabPressResetsStack: ${!!t.tabPressResetsStack}),`,
  );

  const deepLinks = routes.deepLinks.patterns.map(
    (p) => `        DeepLinkPattern(match: ${swiftString(p.match)}, route: ${swiftString(p.route)}),`,
  );
  const push = routes.pushNotificationRouting.map(
    (p) => `        PushRoutingRule(type: ${swiftString(p.type)}, requires: [${p.requires.map(swiftString).join(', ')}], route: .${camel(p.route)}),`,
  );

  return `${HEADER}
import Foundation

public enum RouteID: String, CaseIterable, Hashable, Sendable, Codable {
${routeIds}
}

public enum TabID: String, CaseIterable, Hashable, Sendable, Codable {
${routes.tabs.map((t) => `    case ${camel(t.id)}`).join('\n')}
}

public enum StackID: String, CaseIterable, Hashable, Sendable, Codable {
${stackIds}
}

/// Mirrors react-native-screens presentation options used by the RN app.
public enum RoutePresentation: String, CaseIterable, Hashable, Sendable, Codable {
${presentations.map((p) => `    case ${ident(camel(p))}`).join('\n')}
}

/// Which header component the RN screen renders.
public enum RouteHeader: String, CaseIterable, Hashable, Sendable, Codable {
${headers.map((h) => `    case ${ident(camel(h))}`).join('\n')}
}

public enum RouteParamType: String, Hashable, Sendable, Codable {
    case string, bool, int
}

public struct RouteParamDescriptor: Hashable, Sendable {
    public let name: String
    public let type: RouteParamType
    public let optional: Bool
}

public struct RouteDescriptor: Hashable, Sendable {
    public let id: RouteID
    public let rnPath: String
    public let stack: StackID
    public let presentation: RoutePresentation
    public let animation: String?
    public let animationDurationMs: Int?
    public let params: [RouteParamDescriptor]
    public let header: RouteHeader
    public let headerTitle: String?
    public let headerTitleKey: String?
    public let headerHideBack: Bool
    public let headerRight: String?
    public let headerShowTabs: Bool
    public let headerLogoutOnBack: Bool
    public let headerWithInsets: Bool
    public let backgroundColor: String?
    public let outOfScope: String?
    public var isOutOfScope: Bool { outOfScope != nil }
}

public struct TabDescriptor: Hashable, Sendable {
    public let id: TabID
    public let initialRoute: RouteID
    public let iconFocused: String
    public let iconUnfocused: String
    public let focusedScale: Double
    public let tabPressResetsStack: Bool
}

public struct DeepLinkPattern: Hashable, Sendable {
    public let match: String
    public let route: String
}

public struct PushRoutingRule: Hashable, Sendable {
    public let type: String
    public let requires: [String]
    public let route: RouteID
}

/// A concrete navigation destination with its parameters. Mirrors the Expo Router tree one-to-one.
public enum Route: Hashable, Sendable {
${cases.join('\n')}

    public var id: RouteID {
        switch self {
${idSwitch.join('\n')}
        }
    }

    public var descriptor: RouteDescriptor { Routes.descriptors[id]! }

    /// Parameters as strings, in the same shape Expo Router exposes them via useParams().
    public var params: [String: String] {
        switch self {
${paramSwitch.join('\n')}
        }
    }
}

public enum Routes {
    public static let descriptors: [RouteID: RouteDescriptor] = [
${descriptors.join('\n')}
    ]

    public static let tabs: [TabDescriptor] = [
${tabs.join('\n')}
    ]

    public static let deepLinkScheme = ${swiftString(routes.deepLinks.scheme)}
    public static let associatedDomain = ${swiftString(routes.deepLinks.associatedDomain)}
    public static let deepLinkPatterns: [DeepLinkPattern] = [
${deepLinks.join('\n')}
    ]

    /// Evaluated in order; first match wins (same order as handleNotificationNavigation in the RN app).
    public static let pushRouting: [PushRoutingRule] = [
${push.join('\n')}
    ]
}
`;
}

// ---------------------------------------------------------------------------
// L10n keys + locale copy
// ---------------------------------------------------------------------------

function flattenLocale(obj: Record<string, any>, prefix = ''): [string, string][] {
  return Object.entries(obj).flatMap(([k, v]) =>
    v && typeof v === 'object' ? flattenLocale(v, `${prefix}${k}.`) : [[`${prefix}${k}`, String(v)] as [string, string]],
  );
}

function emitL10nKeys(localesDir: string): { swift: string; locales: string[] } {
  const files = fs.readdirSync(localesDir).filter((f) => f.endsWith('.json')).sort();
  const locales = files.map((f) => path.basename(f, '.json'));
  const en = JSON.parse(fs.readFileSync(path.join(localesDir, 'en.json'), 'utf8'));
  const keys = flattenLocale(en).map(([k]) => k).sort();
  const seen = new Set<string>();
  const cases = keys.map((k) => {
    let c = ident(camel(k.replace(/\./g, '_')));
    while (seen.has(c)) c = `${c}_`;
    seen.add(c);
    return `    case ${c} = ${swiftString(k)}`;
  });
  const swift = `${HEADER}
import Foundation

/// Every translation key present in locales/en.json (the fallback locale). Other locales may omit keys.
public enum L10nKey: String, CaseIterable, Hashable, Sendable {
${cases.join('\n')}
}

public enum L10nCatalog {
    /// Supported locale codes, mirrors lib/i18n.ts supportedLocales (sorted).
    public static let supportedLocales: [String] = [${locales.map(swiftString).join(', ')}]
    public static let defaultLocale = "en"
}
`;
  return { swift, locales };
}

function copyLocales(localesDir: string, destDir: string): void {
  fs.mkdirSync(destDir, { recursive: true });
  for (const f of fs.readdirSync(localesDir).filter((f) => f.endsWith('.json'))) {
    const parsed = JSON.parse(fs.readFileSync(path.join(localesDir, f), 'utf8'));
    fs.writeFileSync(path.join(destDir, f), JSON.stringify(parsed, null, 2) + '\n');
  }
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

export interface GeneratedFile { path: string; contents: string }

export function generateSwift(): GeneratedFile[] {
  const builder = new ModelBuilder(OPENAPI_JSON);
  const model = builder.build();
  const tokens = JSON.parse(fs.readFileSync(TOKENS_JSON, 'utf8'));
  const routes: RoutesJson = JSON.parse(fs.readFileSync(ROUTES_JSON, 'utf8'));
  const l10n = emitL10nKeys(RN_LOCALES_DIR);

  return [
    { path: path.join(SWIFT_API_GENERATED_DIR, 'Models.swift'), contents: emitModels(model, builder.types) },
    { path: path.join(SWIFT_API_GENERATED_DIR, 'Operations.swift'), contents: emitOperations(model) },
    { path: path.join(SWIFT_CORE_GENERATED_DIR, 'Tokens.swift'), contents: emitTokens(tokens) },
    { path: path.join(SWIFT_CORE_GENERATED_DIR, 'Routes.swift'), contents: emitRoutes(routes) },
    { path: path.join(SWIFT_CORE_GENERATED_DIR, 'L10nKeys.swift'), contents: l10n.swift },
  ];
}

export function writeGenerated(files: GeneratedFile[]): void {
  for (const f of files) {
    fs.mkdirSync(path.dirname(f.path), { recursive: true });
    fs.writeFileSync(f.path, f.contents);
  }
}

if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) {
  const files = generateSwift();
  writeGenerated(files);
  copyLocales(RN_LOCALES_DIR, SWIFT_CORE_RESOURCES_LOCALES_DIR);
  for (const f of files) console.log(`wrote ${path.relative(process.cwd(), f.path)} (${f.contents.split('\n').length} lines)`);
  console.log(`copied locales to ${path.relative(process.cwd(), SWIFT_CORE_RESOURCES_LOCALES_DIR)}`);
}
