name: Semantic Pull Request

on:
  pull_request_target:
    types: [opened, edited, synchronize]
    branches-ignore:
      - 'release/**'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
